### ISSUE TITLE
gulp build problem or error

### ISSUE THREAD

**Issue by matriawan** [workswithweb/MQTTBox#1]
after run npm install then to build web apps using "gulp build", always ask to install dependencies ? any solution ?

**Comment by workswithweb** [comment]
Can you provide in which folder you are executing "gulp build"?
Can you provide error stack you are seeing?

**Comment by matriawan** [comment]
please check this http://iot.itnusantara.com/mqttbox
cannot work, seen a lot of problems, hope full you push the "build" code for testing purposes

**Comment by matriawan** [comment]
after replacing or upload app.js from view-source:http://workswithweb.com/mqttbox/app/app.js to my local server, the error doesn't appear again, but the problem now is cannot connect to any broker. please try http://iot.itnusantara.com/mqttbox .hopeful i will get the original source code that has compiled. my email: matriawan@gmail.com

**Comment by workswithweb** [comment]
For now we will send you compiled build. We are rewriting whole app to make
it fast and work in app browsers. New app will be out in a month.

**Comment by matriawan** [comment]
thanks before hope full, i will get the compiled build version, please send to my email: matriawan@gmail.com, big thanks to you.

**Comment by workswithweb** [comment]
Sent latest build to your email.

**Comment by matriawan** [comment]
thanks, awesome, work like a charm. hopeful in next release will be have many improvement and features, specially in QoS of message like delay/jitter/latency, packet loss, cpu/memory usage and much more. big thanks.

**Comment by workswithweb** [comment]
There is new redesigned app with build instructions provided in MQTTBox documentation.
