### ISSUE TITLE
display current connection summary next to connect button 

### ISSUE THREAD

**Issue by ajoslin103** [workswithweb/MQTTBox#11]
it would be a nice touch to see what the connection will be w/the current settings when configuring a connection -- as it is one can't see that until after one attempts the connection

![screen shot 2016-12-14 at 8 50 54 am](https://cloud.githubusercontent.com/assets/443893/21184449/9269ef80-c1da-11e6-81e4-ccb25f1a8dff.png)

(sorry for the clumsy  illustration)

**Comment by workswithweb** [comment]
@ajoslin103 what do you mean by "what the connection will be w/the current settings"?
Do you mean having "Test Connection" button in settings page to test connection before saving?

**Comment by ajoslin103** [comment]
After the connection is opened, there is a description of the connection that is shown in the top of the window, just above the 'publish' div

It would be nice if the connection description could be shown next to the Save button so that we would know what we had configured before we click save and see if it works

<img width="1549" alt="screen shot 2016-12-14 at 2 12 08 pm" src="https://cloud.githubusercontent.com/assets/443893/21197013/e54018ba-c207-11e6-8621-4df4ee3c43e6.png">

**Comment by workswithweb** [comment]
This information is already shown in form. Not sure if this would be useful. Will reopen this issue if more users sends requests to add this preview.

**Comment by ajoslin103** [comment]
ok
