### ISSUE TITLE
would be nice if app remembered last [x] publish topics

### ISSUE THREAD

**Issue by ajoslin103** [workswithweb/MQTTBox#13]
would be nice if app remembered last [x] publish topics

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.

**Comment by ajoslin103** [comment]
I understand, thank you for a great tool - I still use it

cheers!
