### ISSUE TITLE
protobuf support

### ISSUE THREAD

**Issue by pumano** [workswithweb/MQTTBox#14]
MQTTBox support protobuf payload for load testing purposes? If yes, could you provide any guide about it. If no, could you please add support for it?

**Comment by workswithweb** [comment]
@pumano What do you mean by "protobuf payload"?  you provide some examples please

**Comment by pumano** [comment]
I mean google protocol buffers support as payload. i saw protobufjs library can work with protobuf protocol. Its binary protocol. I need to load test my Mqtt broker instance with protobuf messages.

**Comment by workswithweb** [comment]
It doesn't support right now. Will add support in future release.

**Comment by pumano** [comment]
@workswithweb Thank you! I Very important feature for me.

**Comment by pumano** [comment]
@workswithweb can you provide some info about planned release date with this feature?

**Comment by workswithweb** [comment]
@pumano We don't have many requests from users to support protocol buffers right now. This will be low priority compared to other requests. We are working on new tool for load and unit testing [Virtual Things](https://github.com/workswithweb/virtual-things) . Will update this when we have more info.

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
