### ISSUE TITLE
Seems to encode binary data via utf8

### ISSUE THREAD

**Issue by unscriptable** [workswithweb/MQTTBox#15]
Hello!  Thanks for creating MQTTbox!

Currently, the payload is always encoded via utf8 if any of the binary payload types are chosen. 

If I send a payload of 0xe4, I would expect to see a payload of "228" (decimal of 0xe4) received.  Instead, it looks like the payload is is utf8-encoded.  I've tried subscribing with two different MQTT clients and see it in both.  I also tried two different brokers to make sure it wasn't a broker issue.

In MQTTbox I can see "195164" as the Raw payload, which I'm interpreting to mean the bytes 195 and 164 (e.g. `Uint8Array([ 195, 164 ])`).  Here's a screenshot:
![image](https://user-images.githubusercontent.com/46133/29727643-cd7ee6ee-89a2-11e7-935d-355e85124e2c.png)

Actually, it doesn't seem to matter which binary type is chosen, since the source of the error is likely here: https://github.com/workswithweb/MQTTBox/blob/a9db1a9bf511584e330b875fa4b2fa973b31d941/src/app/components/mqttClient/MqttClientPublisher.js#L95

I'd submit a pull request to suggest a fix, but there are too many abstractions and levels of indirection!  I keep getting lost in the code. :(

**Comment by unscriptable** [comment]
Actually, I think I found the line where the mqtt client is called: https://github.com/workswithweb/MQTTBox/blob/a9db1a9bf511584e330b875fa4b2fa973b31d941/src/app/workers/MqttClientConnectionWorker.js#L167

Would it make sense to send an something like this through to this function? 

```js
{
    raw: [0x34], // array of raw data
    dataType: 16 // same as the type chosen in the UI
}
```

and then convert it to a Buffer just before calling the client?  Hmmmm.... does Chrome support Buffer?

**Comment by workswithweb** [comment]
Thanks for detail investigation. This helps a lot. Will fix this in coming release.

**Comment by hhaensel** [comment]
Just stumbled across this today. Are you going to fix this?

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
