### ISSUE TITLE
MQTTBox windows apps can't complete publish load test

### ISSUE THREAD

**Issue by rexksvii** [workswithweb/MQTTBox#16]
Hi, I've using MQTTBox on my windows pc to run the publish load test. The issue is when I set the number of messages more than 1000, the load test will not be completed and stuck in a loop forever 

Here's a screenshot of the issue I mentioned:
![mqttbox1](https://user-images.githubusercontent.com/33199247/32144533-2b017770-bcf5-11e7-9303-63c18c864a25.PNG)

As shown in the screenshot, instance 1 displayed the message "load test completed" but I will never get the result for the test and the test will keep running until I manually hit the Stop Load Test button. 

Here's another screenshot for the setting i've using for the test above
![mqttboxsetting](https://user-images.githubusercontent.com/33199247/32144556-7fee592e-bcf5-11e7-9784-8284e567996a.PNG)

Also, when I hit the Stop Load Test button, I will get an error message like the screenshot below:
![mqttboxerror](https://user-images.githubusercontent.com/33199247/32144577-a7ffb41c-bcf5-11e7-821e-8ff3e9117eb6.PNG)

I'm really appreciate your work on making an easy to use and easy to install mqtt load test tools for windows and hope you can fix/answer my issue as soon as possible. 

Thank you

**Comment by workswithweb** [comment]
Thanks for reporting. Will investigate and fix in next version of app. Also we are building standalone app for load testing which has way more features then existing one. Will send out communication when load testing app is released.

**Comment by rexksvii** [comment]
May I know when the next version/the standalone load test app will be release?

________________________________

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
