### ISSUE TITLE
Load test in chrome plugin, username & password issue

### ISSUE THREAD

**Issue by Laro88** [workswithweb/MQTTBox#17]
It seems like username & password does not work.
I have a couple of mqtt servers running, in house unsecured servers is no problem, load works fine.

Running against an mqtt server that has a username and password seems unavailable, mqttfx is fine on the server, however it does not work with load test
someuser:somepassword@someazureservername.westeurope.cloudapp.azure.com

I have tried with leading mqtt:// and trailing :1883 port number.

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
