### ISSUE TITLE
Avoid Adding duplicated message in publisher window

### ISSUE THREAD

**Issue by waynewu411** [workswithweb/MQTTBox#18]
When publishing a message which is exactly same with any old message in publisher window, it would be better to just move the message to the top of list instead of adding a new one so that we won't have so many same messages in the list.

**Comment by waynewu411** [comment]
One more thing, it would be better if there is a label to indicate the time stamp every message received.

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
