### ISSUE TITLE
Disconnection in always ungraceful

### ISSUE THREAD

**Issue by chimit** [workswithweb/MQTTBox#19]
When I click on a green "Connected" button the connection is closed ungracefully - the last will message is published. Is it an intended behavior? If yes, how to disconnect gracefully?

**Comment by mochi-co** [comment]
I have also been experiencing this problem. I ran a capture in wireshark and it seems like MQTTBox isn't sending a valid disconnect packet on disconnect, it's just terminating the connection (on both tcp and websocket).

**Comment by MarcusMiss** [comment]
This is true: DISCONNECT-packet should be send.

**Comment by xiangwangcheng** [comment]
I have been suffering this problem too, hope somebody can fix it.

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
