### ISSUE TITLE
"Self Signed Certs" TLS Mode only works on Localhost

### ISSUE THREAD

**Issue by MRobertEvers** [workswithweb/MQTTBox#20]
I have been testing an MQTT broker with MQTT Box. When both MQTT Box and the Broker are run on Localhost (any port), the self-signed certs TLS mode works.

However, when I try to use the self-sign certs TLS mode where the Broker is on a remote server, MQTT Box drops the connection as soon as the TLS handshake is done. The logs recorded parts of the TLS handshake followed by a terminated connection.

I tested my setup with another MQTT Client and that client does not drop the connection with the same configuration.

Can anyone replicate this issue?

**Comment by sathyavikram** [comment]
Thanks for reporting.

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
