### ISSUE TITLE
can't connect to local apollo

### ISSUE THREAD

**Issue by dfang** [workswithweb/MQTTBox#21]
```
protocol: mqtt/tcp
host: 127.0.0.1:61613
username: admin
password: password
```

i can connect to local apollo with golang code, where is mqttbox log ?

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
