### ISSUE TITLE
 Subscribe topics Can support hex display?

### ISSUE THREAD

**Issue by wangsheng** [workswithweb/MQTTBox#22]
The current publish topic payload supports hex, but the subscription topic does not support.

If the publish topic payload is selected to be hex array, the subscription topic is directly converted to a string display. But I just want to see the original hex.

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
