### ISSUE TITLE
No clientId for load testing, so it fails

### ISSUE THREAD

**Issue by syberkitten** [workswithweb/MQTTBox#23]
There is no field to pass the clientId / password
when trying to Load Test, so tests cannot connect to broker.

When defining a single connect there are fields
to supply these credentials.

what is the Idea here?

**Comment by svpernova09** [comment]
^ Looking for the answer to this as well, seems silly to not have credentials?

Would also be nice to be able to configure a Publishing Client and use that for the load test.

**Comment by ZyroxCo** [comment]
exato, não tem como entrar credenciais de usuário. O teste de carga parece q executa, mas os dados não são recebidos pelo mqtt. Já existe solução para esse problema?

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
