### ISSUE TITLE
Remaining length header is not correct in Publish Load Test & Subscribe Load Test message.

### ISSUE THREAD

**Issue by bigelastic** [workswithweb/MQTTBox#24]
In Publish Load Test, I create publish message as:
- Topic=test
- QoS=0
- Payload is empty

For this message, the remaining length header should be 6, but it was 8。The Subscribe Load Test also has this problem.
I print out the message hex string as the following

```
Byte     |  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  ...
----------------------------------------------------
Hex      | 30 | 08 | 00 | 04 | 74 | 65 | 73 | 74 |
----------------------------------------------------
```
Screenshot of Publish Load Test Setting

![image](https://user-images.githubusercontent.com/39647776/45137806-befd6880-b1dc-11e8-9266-68b79a8b5a20.png)

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
