### ISSUE TITLE
MQTTBox Helper send packets forever

### ISSUE THREAD

**Issue by aiden-leong** [workswithweb/MQTTBox#28]
When I quit MQTTBox, MQTTBox Helper is not killed.
In `Monitor`, I can see one or more `MQTTBox Helper`.
In Wireshark, I can see endless MQTT PING and PONG packets.
Workaround: Kill them in Monitor.

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
