### ISSUE TITLE
Font Size in MAC app #request

### ISSUE THREAD

**Issue by pbaldovi** [workswithweb/MQTTBox#29]
Hi, 
It would be nice to be able to configure the font size in the MAC App.
Are there instructions available to compile the app on MAC OS?

Thanks for your job

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
