### ISSUE TITLE
Write messages to log file?

### ISSUE THREAD

**Issue by TommySharpNZ** [workswithweb/MQTTBox#30]
Would be great to write the messages to a log file for each Subscriber?

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.

**Comment by datedave** [comment]
I think this tool is fabulous. I used it regularly to debug my interface to AWS. I would love the ability to dump message to a log file.
 
Great App

**Comment by REGIOIGER** [comment]
Great app, very usefull in my day to day work
