### ISSUE TITLE
It is recommended to add export import configuration files, including connection information, pubs, subs

### ISSUE THREAD

**Issue by maxid** [workswithweb/MQTTBox#33]
It is recommended to add export import configuration files, including connection information, pubs, subs, to facilitate sharing and backup.

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
