### ISSUE TITLE
bug in Hex Array

### ISSUE THREAD

**Issue by chenguibang** [workswithweb/MQTTBox#34]
when send in Hex Array has a bug 
send 0x88 recive 0xC2,0x88

**Comment by codebeautiful** [comment]
send Decimal Array also this bug
send all array and revice 194,...

**Comment by hezlog** [comment]
Use ArrayBuffer and Uint8Array to solve problems caused by String.fromCharCode().

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
