### ISSUE TITLE
[Feature] rum multiple windows

### ISSUE THREAD

**Issue by damogongzi** [workswithweb/MQTTBox#36]
The request https://github.com/workswithweb/MQTTBox/issues/12 was closed. I raise a new request. 

I really hope you have the multiple windows feature. It is more easy to debug (sender, receiver). Right now I have to switch back and forth.

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.
