### ISSUE TITLE
Connection Error - Reason

### ISSUE THREAD

**Issue by renerlemes** [workswithweb/MQTTBox#38]
Where I see the details of connection error @workswithweb ?

**Comment by renerlemes** [comment]
?

**Comment by renerlemes** [comment]
?

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.

**Comment by simonachmueller** [comment]
That's what I'm interested too. I'm getting Connection Error, but have no idea why exactly, what I set wrong. The reason would be helpful to see.
