### ISSUE TITLE
Sending Reserver Header packets in Load Test

### ISSUE THREAD

**Issue by nitinet** [workswithweb/MQTTBox#4]
Hi, I am running the load test on my mosca server. There were some error which i found that MqttBox is sending packets of reserved headers. Please refer the following issue.

https://github.com/mqttjs/mqtt-packet/pull/20

**Comment by workswithweb** [comment]
Thanks for reporting. Will look into it.

**Comment by workswithweb** [comment]
We are not modifying Header packets in payload. MQTTBox is just UX layer on top of mqtt.js.
