### ISSUE TITLE
Load tests could not terminate successfully

### ISSUE THREAD

**Issue by ATAKing1023** [workswithweb/MQTTBox#42]
The load test instances randomly stuck at status "in progress" however the load test should be "done". 

When I tried to stop the load test, an error appears.

sorry but I failed to upload the screenshots due to network issue.

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app but not sure if this tool is helping many devs worth my time. Will see if I get more feedback, I would like to re-architecture this app.
