### ISSUE TITLE
Opaque encoding of raw payload

### ISSUE THREAD

**Issue by andersborgabiro** [workswithweb/MQTTBox#43]
Can you please show binary data as a hex string instead, or as delimited decimal values?

This is, as stated, rather opaque:

E.g.

Data:

{"_type":"location","acc":40,"alt":116,"batt":47,"conn":"w","inregions":["Work"],"lat":55.7167103,"lon":13.2273059,"tid":"1","tst":1570040907,"vac":10,"vel":0}

Raw payload:

12334951161211121013458341081119997116105111110344434979999345852484434971081163458494954443498971161163458525544349911111011034583411934443410511011410110310511111011534589134871111141073493443410897116345853534655495455494851443410811111034584951465050555148535744341161051003458344934443411611511634584953554848524857485544341189799345849484434118101108345848125

Interpreted as ASCII:
123: {
34: "
95: _
116: t
121: y
…

Regards,
Anders

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app but not sure if this tool is helping many devs worth my time. Will see if I get more feedback, I would like to re-architecture this app.

**Comment by andersborgabiro** [comment]
Fair enough.

I have no clue how much it is used. We've used it as a reference MQTT client for an IoT platform. Not the only one of course.
