### ISSUE TITLE
UNSUBSCRIBE packet is sent after reconnecting to MQTT broker.

### ISSUE THREAD

**Issue by xiangwangcheng** [workswithweb/MQTTBox#44]
I connected MQTT broker by MQTTBox using cleanSession=false，reconnect=true and subscribed to one topic. Then I cut off the network connection and the mqtt connection was disconnected. 
But when the network restored，the client reconnected to MQTT broker successfully. But after that, an UNSUBSCRIBE packet was sent and the topic was subscribed. Is this a bug or normal?

@sathyavikram

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app but not sure if this tool is helping many devs worth my time. Will see if I get more feedback, I would like to re-architecture this app.
