### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by DavidJeyapaul** [workswithweb/MQTTBox#45]
I have installed the mqttbox on my laptop. I m creating the client. but it is showing it is not connected to the broker. I m not changing any settings. I m just giving the MQTTclient Name and clicked Save.

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app but not sure if this tool is helping many devs worth my time. Will see if I get more feedback, I would like to re-architecture this app.
