### ISSUE TITLE
MQTTBox is missing on the Apple AppStore

### ISSUE THREAD

**Issue by thomasnordquist** [workswithweb/MQTTBox#46]
Error message from the AppStore ~"This App is currently not available in your country or region"

<img width="439" alt="Bildschirmfoto 2019-11-04 um 10 15 12" src="https://user-images.githubusercontent.com/7721625/68110034-572fd400-feec-11e9-8f75-ded671953d36.png">

**Comment by msenebald** [comment]
same here :(

**Comment by sathyavikram** [comment]
I need to renew my developer account.
I have not been updating this tool or repo for long time.
I had plan of rewriting this app but not sure if this tool is helping many devs worth my time. Will see if I get more feedback, I would like to re-architecture this app.
