### ISSUE TITLE
Certificate was expired, but it can connected.

### ISSUE THREAD

**Issue by enrahmad** [workswithweb/MQTTBox#47]
I have mqtt broker with let's encrypt certificate. I can connect using mqttbox (mqtt/tls) though my cert was expired.

Can you explain it? 

FYI, I can connect mqtt broker but I can not pub-sub message.

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app but not sure if this tool is helping many devs worth my time. Will see if I get more feedback, I would like to re-architecture this app.
