### ISSUE TITLE
No full screen please

### ISSUE THREAD

**Issue by cimpok** [workswithweb/MQTTBox#48]
Could you please change the default behaviour not to open full screen.
This is a development tool to be used side-by-side with other tools, editors, IDE, etc on the screen. It is very annoying having to police its arrogance each time it loads itself over everything else on the screen.

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app but not sure if this tool is helping many devs worth my time. Will see if I get more feedback, I would like to re-architecture this app.
