### ISSUE TITLE
Pango-ERROR Harfbuzz version too old (1.2.7)

### ISSUE THREAD

**Issue by jmhernandez-circutor** [workswithweb/MQTTBox#49]
I've got this error:

```
(MQTTBox:90482): Pango-ERROR **: 14:24:30.973: Harfbuzz version too old (1.2.7)

fish: 'MQTTBox' terminated by signal SIGTRAP (Trace or breakpoint trap)
```
I've pango 1:1.44.7+11+g73b46b04-1.

It seems that the new pango version is not compatible with harfbuzz old versions.

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app but not sure if this tool is helping many devs worth my time. Will see if I get more feedback, I would like to re-architecture this app.

**Comment by ofields** [comment]
For what it's worth, I've found the tool to be extremely useful. What kind of architecture were you looking to change to?
