### ISSUE TITLE
sending byte arrays

### ISSUE THREAD

**Issue by spott** [workswithweb/MQTTBox#5]
MQTT seems to allow for byte arrays to be sent as a payload.

Is this possible to do in MQTT box? and if it is, it should be advertised, and if it isn't, is there a way to make it possible?

**Comment by workswithweb** [comment]
Not right now. We are in process of implementing sending "binary data". Will keep this issue open until we push this fix.Thanks for reporting.

**Comment by spott** [comment]
No problem.  I'll be perfectly happy with being able to send binary data of any kind.

**Comment by workswithweb** [comment]
@spott can you provide sample byte array data you are trying to send?

**Comment by spott** [comment]
They are bit masks for controlling an alarm clock, essentially a compressed struct in binary, with start and stop bytes.

something like:

  0x00,0x03,0x12,0x88,0x88,0x15,0xFF,0xFF,0x02,0x22,0x03,0x00,0x1E,0x1F,0xFF,0x2F,0xFF,0x3A,0xAA,0xFF,0xFF,...

How do you plan on representing binary data?

**Comment by workswithweb** [comment]
We have added new attribute "Payload Type". User can select "type of payload" he needs to send and specify comma separated values in "payload" textbox if payload type is other than string. Does this work for you ?
![screen shot 2016-10-28 at 12 52 56 pm](https://cloud.githubusercontent.com/assets/17054312/19816645/be61dde2-9d0d-11e6-846c-a1b189169a73.png)

**Comment by spott** [comment]
That looks great!

**Comment by workswithweb** [comment]
@spott We have deployed changes to  http://workswithweb.com/mqttbox/app
Please review and provide your feedback. 
We want to migrate this to native apps if everything looks good.

**Comment by workswithweb** [comment]
implemented in latest release. closing this issue.

**Comment by leecan95** [comment]
I can not send byte data >127

**Comment by leecan95** [comment]
byte array, decimal and hexa not working
