### ISSUE TITLE
Load Test Does not have User/Password setting

### ISSUE THREAD

**Issue by nikhilve99** [workswithweb/MQTTBox#7]
Hi 

When we try to do publish test, Our MQTT broker requires authentication and Load test does not have those setting. How to use username and password in load testing

**Comment by workswithweb** [comment]
Load test does not support authentication right now. We will add support to password and
certificate auth very soon.

Right now password and device certificate authentication is available only for
mqtt clients.

**Comment by workswithweb** [comment]
Will keep this open until we add support for User/Password/SSL/TLS support for load test

**Comment by briantully** [comment]
any update on this? Specifically looking for TLS auth support for load testing things on Amazon IoT. Anyone know of any other tool that supports load testing things over mqtt with TLS?

**Comment by workswithweb** [comment]
@briantully We are working on new tool https://github.com/workswithweb/virtual-things to add load test. We will be adding more features to this tool. We will be releasing this tool in couple of months

**Comment by gwainer** [comment]
Hello, is supporting certificate and password for load testing still planned?

**Comment by workswithweb** [comment]
yes. we are in process of developing new app for this. Will release shortly and update this ticket

**Comment by FulvioSpelta** [comment]
+1

**Comment by anandxp** [comment]
@workswithweb 

Any update on load testing with authentication !!
Waiting for this feature in MQTTBox for a long time

**Comment by workswithweb** [comment]
@anandxp we are working on new tool for load testing (virtual-things). Will release it ASAP.

**Comment by xiangwangcheng** [comment]
Almost 3 years passed and any update on this?

**Comment by ZyroxCo** [comment]
também estou esperando a solução. Se criaram outra app, por favor informem qual é.

**Comment by davidjmallar** [comment]
Any update? This is the best mqtt tool out there, but for load testing I can not use it because of this request from 2016 :(

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I have plan of rewriting this app but not sure it need to do it or not. Depending on feedback I get, I may rewrite this tool with better architecture

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app but not sure if this tool is helping many devs worth my time.

**Comment by holopekochan** [comment]
this tool is good. I also want to test with the username and password on my wss

**Comment by xiangwangcheng** [comment]
@sathyavikram  This tool is helping my team! It's very useful and please don't give it up. -)

**Comment by sathyavikram** [comment]
Thanks for your support. Will see if there are more people interested

**Comment by handgr** [comment]
same, waiting for authenticate for oad tests
