### ISSUE TITLE
app does not remember last window size and position

### ISSUE THREAD

**Issue by ajoslin103** [workswithweb/MQTTBox#8]
app should remember last window size and position, alway opening to fullscreen is bothersome

**Comment by workswithweb** [comment]
@ajoslin103 what platform of app you are referring to? (MAC/Windows/Linux/Chrome).
please provide more details.

**Comment by ajoslin103** [comment]
ah! apologies, mac os x -- I like the app a lot, and much prefer it to running the java mqtt.fx

**Comment by workswithweb** [comment]
Thanks. Will keep this issue open until we push the fix in next release.

**Comment by chimit** [comment]
Have the same problem.

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.

**Comment by ajoslin103** [comment]
I understand, thank you for a great tool - I still use it

cheers!
