### ISSUE TITLE
close icon overlaps scrollbar

### ISSUE THREAD

**Issue by ajoslin103** [workswithweb/MQTTBox#9]
![screen shot 2016-12-13 at 5 45 19 pm](https://cloud.githubusercontent.com/assets/443893/21162551/fea15456-c15b-11e6-9e0b-b0601e9d51f0.png)

if you drag to resize the payload textarea below the bottom of the enclosing div then the parent scrolls -- the close icon then overlaps the scrollbar

**Comment by workswithweb** [comment]
@ajoslin103 Nice Job!!! Thanks for raising multiple issues. 👍 
Encourage you to find more issues to make tool more robust.

**Comment by ajoslin103** [comment]
will do my best :)

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app with more features but not sure if this tool is helping many devs worth my time. Will see if I can get more feedback, I would re-architecture this app with more features.

**Comment by ajoslin103** [comment]
I understand, thank you for a great tool - I still use it

cheers!
